#!/bin/bash
# Plot all data in directory with plot.py
clear
arg=""

if [ "$1" == "pre" ]
then
	arg="-p"
elif [ "$1" == "den" ]
then
	arg="-d"
elif [ "$1" == "hii" ]
then
	arg="-h"
fi
ls tmp/data2D_*.txt | parallel --gnu ./plot.py -i {} $arg
