#!/bin/bash
pad=4
function zpad {
	formatting="%0"$2"d"
	[[ "$1" =~ ([0-9]+)\. ]]
	num=${BASH_REMATCH[1]}
	paddednum=`printf $formatting $((10#$num))`
	mv $1 ${1/$num/$paddednum}
}
export -f zpad
ls tmp/data2D_*.txt | parallel --gnu zpad {} 3


