-- Torch Parameters
Parameters = {
	Integration = {
		density_scale =              1,
		pressure_scale =             1,
		time_scale =                 1,
		spatial_order =              1,
		temporal_order =             2,
		simulation_time =            0.4,
		radiation_on =               false,
		cooling_on =                 false,
		debug =                      false,
		setup_id =                   0,
		output_directory =           "tmp/",
		initial_conditions =         "patch_test.txt",
	},
	Grid = {
		no_dimensions =              1,
		no_cells_x =                 100,
		no_cells_y =                 1,
		no_cells_z =                 1,
		geometry =                   "cartesian",
		side_length =                1,
		left_boundary_condition_x =  "reflecting",
		left_boundary_condition_y =  "reflecting",
		left_boundary_condition_z =  "reflecting",
		right_boundary_condition_x = "reflecting",
		right_boundary_condition_y = "reflecting",
		right_boundary_condition_z = "reflecting",
		Patch = {
			filename = "patch.txt",
			offset_x = 5,
			offset_y = 5,
			offset_z = 0,
		}
	},
	Hydrodynamics = {
		gamma =                      1.67,
		density_floor =              1.0e-25,
		pressure_floor =             1.0e-17,
		temperature_floor =          1.0e-20,
		riemann_solver =             "RotatedHLLC",
		slope_limiter =              "albada",
	},
	Radiation = {
		K1 =                         0.2,
		K2 =                         0.0,
		K3 =                         0.0,
		K4 =                         0.0,
		photoion_cross_section =     6.3e-18,
		case_b_recombination_coeff = 2.59e-13,
		tau_0 =                      0.6,
		minimum_hii_fraction =       0,
		temperature_hi =             300,
		temperature_hii =            10000,
		mass_fraction_hydrogen =     1.0,
		integration_scheme =         "implicit",
		collisions_on =              false,
		coupling =                   "neq",
	},
	Thermodynamics = {
		heating_amplification =      0.001,
		thermo_hii_switch =          -1,
	},
	Star = {
		on =                         false,
		cell_position_x =            0,
		cell_position_y =            0,
		cell_position_z =            0,
		snap_to_face_left_x =        true,
		snap_to_face_left_y =        false,
		snap_to_face_left_z =        false,
		snap_to_face_right_x =       false,
		snap_to_face_right_y =       false,
		snap_to_face_right_z =       false,
		photon_energy =              2.976e-11,
		photon_rate =                2.2e48,
		wind_radius_in_cells =       10,
		mass_loss_rate =             6.34e19,
		wind_velocity =              2.0e8,
		wind_temperature =           10000,
	},
}
