#!/bin/bash

if [ "$2" == "" ] || [ "$1" == "" ] || [ "$1" == "-help" ] || [ "$1" == "-h" ] ; then
	echo "usage: "$0" <dataset_id> <casa_image_dir>"
else
	if [[ $2 =~ ^simobs_(.*)_(.*)$ ]]; then
		mv $2 "../Torch/data/cornish_$1/${BASH_REMATCH[1]}/radio_${BASH_REMATCH[2]}"
	fi
fi
