#!/bin/bash
# Clean up unnecessary files in directory

if [ "$1" == "" ] || [ "$1" == "-help" ] ; then
	echo "usage: cleanup <directory_name>"
else
	#read -p "Are you sure? (yes/no)" -n 3 -r
	#echo    # (optional) move to a new line
	#if [[ $REPLY =~ ^yes$ ]]
	#then
		rm $1/*.txt
		rm $1/*.png
		rm $1/*.jpg
		rm $1/*.pdf
	#fi
fi
