#!/bin/bash

function video_order {
	formatting="%0"$3"d"
	[[ "$1" =~ _([0-9]+)\. ]]
	num=${BASH_REMATCH[1]}
	paddednum=`printf $formatting $((10#$2))`
	if [ "$1" != "${1/_$num/_$paddednum}" ]; then
		mv $1 ${1/_$num/_$paddednum}
		echo $1" -> "${1/_$num/_$paddednum}
	fi
}

if [ "$1" == "" ] || [ "$2" == "" ] || [ "$1" == "-help" ] || [ "$1" == "-h" ] ; then
	echo "usage: "$0" <data_set> <directory_name>"
else
	export -f video_order
	pad=3
	i=0
	for file in $2/$1_*.txt.gz
	do
		echo $file
		video_order $file $i $pad
		i=`expr $i + 1`
	done
	echo $0": renumbered data2D_\*.txt.bz2 files for avidemux"
fi
