#!/bin/bash

function zpad {
	formatting="%0"$3"d"
	[[ "$2" =~ _([0-9]+)\. ]]
	num=${BASH_REMATCH[1]}
	paddednum=`printf $formatting $((10#$num))`
	if [ "$2" != "${2/_$num/_$paddednum}" ]; then
		mv $2 ${2/$1_$num/$1_$paddednum}
	fi
}

if [ "$1" == "" ] || [ "$2" == "" ] || [ "$1" == "-help" ] || [ "$1" == "-h" ] ; then
	echo "usage: "$0" <data_set> <directory_name>"
else
	pad=3
	export -f zpad
	ls $2/$1_*.txt.gz | parallel --gnu zpad $1 {} $pad
	echo "$0: padded $2/$1_*.txt.gz files with zeros"
fi
