#!/bin/bash

function num_shift {
	formatting="%0"$2"d"
	[[ "$3" =~ _([0-9]+)\. ]]
	num=${BASH_REMATCH[1]}
	stripped_num=`echo $num|sed 's/^0*//'`
	shifted_num=$((stripped_num+$1))
	shifted_num=`printf $formatting $((10#$shifted_num))`
	if [ "$3" != "${3/_$num/_$shifted_num}" ]; then
		mv $3 ${3/_$num/_$shifted_num}".num_shifted"
	fi
}

function remove_ext {
	final=`echo $1|sed 's/\.num_shifted$//'`
	mv $1 $final
}

if [ "$1" == "" ] || [ "$2" == "" ] || [ "$3" == "" ] || [ "$1" == "-help" ] || [ "$1" == "-h" ] ; then
	echo "usage: shift_num <data_set> <shift_by> <directory_name>"
else
	pad=3
	export -f num_shift
	ls $3/$1_*.txt.bz2 | parallel --gnu num_shift $2 $pad {}
	export -f remove_ext
	ls $3/$1_*.txt.bz2.num_shifted | parallel --gnu remove_ext {}
fi
